---
title: "Piramide"
author: "Jorge"
date: '2022-04-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "piramide"
output: html_document
date: '2022-04-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("pyramid")
require(pyramid)
Hombres <- c(60,50,40,30,25,20,15,10) ####### Población de hombres 
names(Hombres) <- c('0-5','10-19','20-29','30-39','40-49','50-59','60-39','70+') #### grupos de edad
Mujeres <-c(80,70,50,30,28,23,18,15) #### población mujeres 


```
## Gráfica de prirámide 
```{r}
X11()
pyramids(Left=hombres,Llab="Hombres",Right=mujeres,Rlab="Mujeres",Clab="Grupos de edad",Laxis=c(0,50,100),Csize=1, main="Gráfica 1: Ejemplo de pirámide poblacional Clase de demografía",Lcol= "red",Rcol= "grey")

ags <-read.csv(file.choose())


agsmuj<- ags %>%
as_tibble () %>% 
mutate (gpoeda =case_when (EDAD >=0 & EDAD<= 4 ~ 1,
EDAD >=5 & EDAD<= 9 ~ 2,
EDAD >=10 & EDAD<= 14 ~ 3,
EDAD >=15 & EDAD<= 19 ~ 4,
EDAD >=20 & EDAD<= 24 ~ 5,
EDAD >=25 & EDAD<= 130 ~ 6,
EDAD ==999 ~ 7), conyu = case_when(SITUA_CONYUGAL == 1 | 
(SITUA_CONYUGAL== 5 & SITUA_CONYUGAL >= 7) ~ 1, 
SITUA_CONYUGAL >= 2 & SITUA_CONYUGAL <= 4 ~ 2, 
SITUA_CONYUGAL == 8 ~ 3, 
SITUA_CONYUGAL == 9 ~ 4)) %>%
filter(SEXO==3 &(EDAD>=50 & EDAD<=130))
table (agsmuj$SEXO)
table (agsmuj$EDAD)

agsmuj1<- ags %>%
as_tibble () %>% 
mutate (gpoeda =case_when (EDAD >=0 & EDAD<= 4 ~ 1,
EDAD >=5 & EDAD<= 9 ~ 2,
EDAD >=10 & EDAD<= 14 ~ 3,
EDAD >=15 & EDAD<= 19 ~ 4,
EDAD >=20 & EDAD<= 24 ~ 5,
EDAD >=25 & EDAD<= 130 ~ 6,
EDAD ==999 ~ 7), conyu = case_when(SITUA_CONYUGAL == 1 | 
(SITUA_CONYUGAL== 5 & SITUA_CONYUGAL >= 7) ~ 1, 
SITUA_CONYUGAL >= 2 & SITUA_CONYUGAL <= 4 ~ 2, 
SITUA_CONYUGAL == 8 ~ 3, 
SITUA_CONYUGAL == 9 ~ 4)) %>%
filter(SEXO==3 &(EDAD>=50 & EDAD<=130))%>%
select (SEXO, EDAD, MUN, INGTRMEN, SITUA_CONYUGAL, conyu, gpoeda)



agsmuj1%>%
group_by (MUN)%>%
summarise (mediana = median (INGTRMEN, na.rm = T))
  
  
  
names (agsmuj)


table (ags$gpoeda)
install.packages("questionr")
require(questionr)

wtd.table (ags$SEXO, weights=ags$FACTOR)
wtd.table (ags$gpoeda, weights=ags$FACTOR)
table (ags$gpoeda)

base2 <- ags%>%
as_tibble() %>%
filter(MUN == 1 | MUN== 2)




```